source ~/.config/nushell/nu_scripts/custom-completions/bat/bat-completions.nu
source ~/.config/nushell/nu_scripts/custom-completions/curl/curl-completions.nu
source ~/.config/nushell/nu_scripts/custom-completions/docker/docker-completions.nu
source ~/.config/nushell/nu_scripts/custom-completions/gh/gh-completions.nu
source ~/.config/nushell/nu_scripts/custom-completions/git/git-completions.nu
source ~/.config/nushell/nu_scripts/custom-completions/less/less-completions.nu
source ~/.config/nushell/nu_scripts/custom-completions/make/make-completions.nu
source ~/.config/nushell/nu_scripts/custom-completions/npm/npm-completions.nu
source ~/.config/nushell/nu_scripts/custom-completions/pnpm/pnpm-completions.nu
source ~/.config/nushell/nu_scripts/custom-completions/rg/rg-completions.nu
source ~/.config/nushell/nu_scripts/custom-completions/ssh/ssh-completions.nu
source ~/.config/nushell/nu_scripts/custom-completions/cargo/cargo-completions.nu
source ~/.config/nushell/nu_scripts/custom-completions/rustup/rustup-completions.nu
source ~/.config/nushell/nu_scripts/custom-completions/auto-generate/completions/aws.nu
source ~/.config/nushell/nu_scripts/custom-completions/auto-generate/completions/terraform.nu
source ~/.config/nushell/nu_scripts/custom-completions/auto-generate/completions/fzf.nu
source ~/.config/nushell/nu_scripts/custom-completions/auto-generate/completions/rustc.nu

use ~/.config/nushell/nu_scripts/modules/aws/select-aws-profile.nu
use ~/.config/nushell/nu_scripts/modules/virtual_environments/venv.nu
